version: '3.9'

services:

 db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB= dbs-db
    ports:
      - '5432:5432'
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
volumes:
  db:
    driver: local

networks:
  mynetwork:
